In [102]:
import pandas as pd
df = pd.read_csv("data.csv", encoding='EUC-KR')
df.head()

selections = ['서울특별시','부산광역시', '대구광역시',
                    '경상북도', '경상남도', '광주광역시', '대전광역시', 
                    '울산광역시', '경기도', '충청북도', '충청남도', 
                    '전라북도', '전라남도', '강원도', '인천광역시']

# 발생건수,사상자수,사망자수,중상자수,경상자수,부상신고자수
count1 = [0,0,0,0,0,0] #서울특별시
count2 = [0,0,0,0,0,0] #부산광역시
count3 = [0,0,0,0,0,0] #대구광역시
count4 = [0,0,0,0,0,0] #경상북도
count5 = [0,0,0,0,0,0] #경상남도
count6 = [0,0,0,0,0,0] #광주광역시
count7 = [0,0,0,0,0,0] #대전광역시
count8 = [0,0,0,0,0,0] #울산광역시
count9 = [0,0,0,0,0,0] #경기도
count10 = [0,0,0,0,0,0] #충청북도
count11 = [0,0,0,0,0,0] #충청남도
count12 = [0,0,0,0,0,0] #전라북도
count13 = [0,0,0,0,0,0] #전라남도
count14 = [0,0,0,0,0,0] #강원도
count15 = [0,0,0,0,0,0] #인천광역시

for i in range(len(df)):
    #print(df.iloc[i,4])
    for slt in selections:
        if slt in df.iloc[i,4]:
            df2 = df.iloc[i, [6,7,8,9,10,11]]       
            if slt == '서울특별시':
                #print(slt, df2[0], df2[1], df2[2], df2[3], df2[4], df2[5])
                count1[0]+= df2[0]
                count1[1]+= df2[1]
                count1[2]+= df2[2]
                count1[3]+= df2[3]
                count1[4]+= df2[4]
                count1[5]+= df2[5]
            elif slt == '부산광역시':
                #print(slt, df2[0], df2[1], df2[2], df2[3], df2[4], df2[5])
                count2[0]+= df2[0]
                count2[1]+= df2[1]
                count2[2]+= df2[2]
                count2[3]+= df2[3]
                count2[4]+= df2[4]
                count2[5]+= df2[5]
            elif slt == '대구광역시':
                count3[0]+= df2[0]
                count3[1]+= df2[1]
                count3[2]+= df2[2]
                count3[3]+= df2[3]
                count3[4]+= df2[4]
                count3[5]+= df2[5]
            elif slt == '경상북도':
                count4[0]+= df2[0]
                count4[1]+= df2[1]
                count4[2]+= df2[2]
                count4[3]+= df2[3]
                count4[4]+= df2[4]
                count4[5]+= df2[5]
            elif slt == '경상남도':
                count5[0]+= df2[0]
                count5[1]+= df2[1]
                count5[2]+= df2[2]
                count5[3]+= df2[3]
                count5[4]+= df2[4]
                count5[5]+= df2[5]
            elif slt == '광주광역시':
                count6[0]+= df2[0]
                count6[1]+= df2[1]
                count6[2]+= df2[2]
                count6[3]+= df2[3]
                count6[4]+= df2[4]
                count6[5]+= df2[5]
            elif slt == '대전광역시':
                count7[0]+= df2[0]
                count7[1]+= df2[1]
                count7[2]+= df2[2]
                count7[3]+= df2[3]
                count7[4]+= df2[4]
                count7[5]+= df2[5]
            elif slt == '울산광역시':
                count8[0]+= df2[0]
                count8[1]+= df2[1]
                count8[2]+= df2[2]
                count8[3]+= df2[3]
                count8[4]+= df2[4]
                count8[5]+= df2[5]          
            elif slt == '경기도':
                count9[0]+= df2[0]
                count9[1]+= df2[1]
                count9[2]+= df2[2]
                count9[3]+= df2[3]
                count9[4]+= df2[4]
                count9[5]+= df2[5]
            elif slt == '충청북도':
                count10[0]+= df2[0]
                count10[1]+= df2[1]
                count10[2]+= df2[2]
                count10[3]+= df2[3]
                count10[4]+= df2[4]
                count10[5]+= df2[5]
            elif slt == '충청남도':
                count11[0]+= df2[0]
                count11[1]+= df2[1]
                count11[2]+= df2[2]
                count11[3]+= df2[3]
                count11[4]+= df2[4]
                count11[5]+= df2[5]
            elif slt == '전라북도':
                count12[0]+= df2[0]
                count12[1]+= df2[1]
                count12[2]+= df2[2]
                count12[3]+= df2[3]
                count12[4]+= df2[4]
                count12[5]+= df2[5]
            elif slt == '전라남도':
                count13[0]+= df2[0]
                count13[1]+= df2[1]
                count13[2]+= df2[2]
                count13[3]+= df2[3]
                count13[4]+= df2[4]
                count13[5]+= df2[5]
            elif slt == '강원도':
                count14[0]+= df2[0]
                count14[1]+= df2[1]
                count14[2]+= df2[2]
                count14[3]+= df2[3]
                count14[4]+= df2[4]
                count14[5]+= df2[5]
            elif slt == '인천광역시':
                count15[0]+= df2[0]
                count15[1]+= df2[1]
                count15[2]+= df2[2]
                count15[3]+= df2[3]
                count15[4]+= df2[4]
                count15[5]+= df2[5]

results = [count1, count2, count3, count4, count5, count6, count7, count8, count9, count10,
          count11, count12, count13, count14, count15]

#from matplotlib import font_manager, rc
#font_name = font_manager.FontProperties(fname="c:/Windows/Fonts/malgun.ttf").get_name()
#rc('font', family=font_name)

#print(results)
#titles = ['발생건수','사상자수','사망자수','중상자수','경상자수','부상신고자수']
#import matplotlib.pyplot as plt

#for count in results:
#    plt.plot(titles,count)
#    #plt.bar(titles, count)
#plt.show()